# Generated by Django 4.0.6 on 2022-07-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_product_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publsihYear',
            new_name='publishYear',
        ),
    ]
